name: upgrade_util
description: "An in-app update plugin that supports redirecting to app stores for updates, previewing reviews, and writing reviews."
version: 3.1.0
homepage: https://github.com/LeoLi-Byte/
repository: https://github.com/LeoLi-Byte/upgrade_util/
issue_tracker: https://github.com/LeoLi-Byte/upgrade_util/issues/

environment:
  sdk: ^3.11.0
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.leoli.plugin.upgrade_util
        pluginClass: UpgradeUtilPlugin
      ios:
        pluginClass: UpgradeUtilPlugin
